---
title: エラーを2度処理する
tags:
  - Go
private: true
updated_at: '2024-09-02T20:56:08+09:00'
id: 5b7417f6c8d50dfcce99
organization_url_name: null
slide: false
ignorePublish: false
---
# エラーを2度処理する

```go
func GetRoute(srcLat, srcLng, dstLat, dstLng float32) (Route, error) {
	err := validateCoordinates(srcLat, srcLng)
	if err != nil {
         // ログを記録して、エラーを返す
		log.Println("failed to validate source coordinates")
		return Route{}, err
	}

	err = validateCoordinates(dstLat, dstLng)
	if err != nil {
         // ログを記録して、エラーを返す
		log.Println("failed to validate target coordinates")
		return Route{}, err
	}

	return getRoute(srcLat, srcLng, dstLat, dstLng)
}

func validateCoordinates(lat, lng float32) error {
	if lat > 90.0 || lat < -90.0 {
         // ログを記録して、エラーを返す
		log.Printf("invalid latitude: %f", lat)
		return fmt.Errorf("invalid latitude: %f", lat)
	}
	if lng > 180.0 || lng < -180.0 {
         // ログを記録して、エラーを返す
		log.Printf("invalid longitude: %f", lng)
		return fmt.Errorf("invalid longitude: %f", lng)
	}
	return nil
}
```

validateCoordinatesでinvalid latitudeエラーメッセージやinvalid longitudeエラーメッセージが、ログの記録と返されるエラーの両方で繰り返されており、コードが煩雑になっている。また、例えば緯度の値が無効である状態でコードを実行すると、次のような行がログに記録される。

```txt
2021/06/01 20:00:00 invalid latitude: 200.000000
2021/06/01 20:00:00 failed to validate source coordinates
```

(go100tipsの著者の)経験則上、エラーは1度だけ処理されるべきである。
エラーをログに記録することはエラーを処理することであり、エラーを返すことも同じ。ゆえに、ログを記録するか、エラーを返すかのどちらかであるべきで両方を同時に行うべきではない。

エラーを1度だけ処理するように実装してみると以下のようになる。

```go
func GetRoute(srcLat, srcLng, dstLat, dstLng float32) (Route, error) {
	err := validateCoordinates2(srcLat, srcLng)
	if err != nil {
        // エラーだけを返す
		return Route{}, err
	}

	err = validateCoordinates(dstLat, dstLng)
	if err != nil {
        // エラーだけを返す
		return Route{}, err
	}

	return getRoute(srcLat, srcLng, dstLat, dstLng)
}

func validateCoordinates(lat, lng float32) error {
	if lat > 90.0 || lat < -90.0 {
		return fmt.Errorf("invalid latitude: %f", lat)
	}
	if lng > 180.0 || lng < -180.0 {
		return fmt.Errorf("invalid longitude: %f", lng)
	}
	return nil
}
```


このようにすることで書くエラーは直接返されることによって1度だけ処理される。また、GetRouteの呼び出し元が起こり得るエラーをログに記録すると仮定すると、緯度の値が無効である場合に、以下のようなメッセージを表示する。

```txt
2021/06/01 20:00:00 invalid latitude: 200.000000
```

これは完璧でない。というのも、元のコードではvalidateCoordinatesのどちらの呼び出しが失敗したのか判断できたが、その情報が失われている。ゆえにエラーに文脈情報を追加する必要がある。つまり、エラーラッピングする必要がある。

```go
func GetRoute(srcLat, srcLng, dstLat, dstLng float32) (Route, error) {
	err := validateCoordinates(srcLat, srcLng)
	if err != nil {
		return Route{},
			fmt.Errorf("failed to validate source coordinates: %w", err)
	}

	err = validateCoordinates(dstLat, dstLng)
	if err != nil {
		return Route{},
			fmt.Errorf("failed to validate target coordinates: %w", err)
	}

	return getRoute(srcLat, srcLng, dstLat, dstLng)
}
```

このログは以下のようになる。

```txt
2021/06/01 20:00:00 invalid latitude: 200.000000
→  invalid latitude: 200.000000
```

